### ISSUE TITLE
Crash using EvaporateTextView!

### ISSUE THREAD

**Issue by Shuffler** [hanks-zyh/HTextView#54]
EvaporateTextView bText = (EvaporateTextView) myInflater.findViewById(R.id.bText);
        bText .animateText("Hi, There!");
```
      <com.hanks.htextview.evaporate.EvaporateTextView
            android:id="@+id/bText"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:textColor="@color/white"
            android:textSize="20sp" />

````
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference at com.hanks.htextview.evaporate.EvaporateText.animateText(EvaporateText.java:52) at com.hanks.htextview.evaporate.EvaporateTextView.animateText(EvaporateTextView.java:46) at com.swish.perfectshot.fragment.IntroFragment.onCreateView(IntroFragment.java:83)

**Comment by Shoureken** [comment]
same error

**Comment by thiagovictorino** [comment]
+1

**Comment by GuilhermeFelipe616** [comment]
+1

**Comment by danielsilver2** [comment]
+1

**Comment by rhbarauna** [comment]
+1

**Comment by JoseluGallardo** [comment]
+1 Any solution?

**Comment by fillbirdpa** [comment]
+1

**Comment by iielse** [comment]
+1

**Comment by kinsleykajiva** [comment]
clearly, this library can not be used in production, I would think it really needs more time to be fixed, several issues are still unresolved.

**Comment by smasini** [comment]
I have the same errore for the ScaleTextView and I resolve like this:

      
       ViewTreeObserver vto = scaleTextView.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                scaleTextView.getViewTreeObserver().removeOnGlobalLayoutListener(this);
                scaleTextView.animateText("YOUR NIGHT LIFE PLANNER");
            }
        });

This is because android.text.Layout is null untill the view is ready.

**Comment by hanks-zyh** [comment]
fixed it

**Comment by Miljan9602** [comment]
Still got this error. 
E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference

**Comment by Sandrichka22** [comment]
I also experienced the same error on version 0.1.0 and 0.1.1 of the library.  I am now going to see if 0.1.6 has the problem fixed...

**Comment by tanish2k09** [comment]
Umm... This is marked closed but I'm still getting this error.

Using version 0.1.6 right now.
So I'm reading the cpufreq continuously (at 1500ms intervals) using a thread and then update a HTextview (scale) on the main (UI) thread using a runnable and posting it using a handler with Looper.getmainlooper(). The runnable has the animateText call in it.

The thread is run from within a fragment. So I stop the thread onStop of the fragment to stop extra resource consumption by the thread and I restart the thread onResume of the fragment. Now if I turn off my screen, it calls onStop (and I have confirmed it is called) which stops the thread but when I turn the screen back on again, onResume is called and I restart the thread and that's when the crash happens and dumps the following log : 

`java.lang.NullPointerException: Attempt to invoke virtual method 'float android.text.Layout.getLineLeft(int)' on a null object reference
        at com.hanks.htextview.scale.ScaleText.drawFrame(ScaleText.java:98)
        at com.hanks.htextview.base.HText.onDraw(HText.java:114)
        at com.hanks.htextview.scale.ScaleTextView.onDraw(ScaleTextView.java:44)
        at android.view.View.draw(View.java:17209)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17212)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.draw(View.java:17212)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17212)
        at android.widget.ScrollView.draw(ScrollView.java:1737)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.support.constraint.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1966)
        at android.view.View.draw(View.java:17212)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17212)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1254)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
08-25 17:34:16.186 29787-29787/com.tanish2k09.vkm.dev E/AndroidRuntime:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16186)
        at android.view.View.draw(View.java:16975)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17212)
        at com.android.internal.policy.DecorView.draw(DecorView.java:758)
        at android.view.View.updateDisplayListIfDirty(View.java:16191)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)`

I have tried using a simple android textview instead of HTextview and it works fine. And also from looking at the log I'm confident there's nothing wrong with my own logic implementations. Looks like an internal issue with the HTextview so I dropped this post here.

Edit 1 :
I noticed a weird thing. If I turn off and then turn on my screen, the app crashes with the above log.
But, if I switch to some other app first, like opening settings from the notifications area, the app doesn't crash in bg, and it also resumes fine after picking it from recents. What's weirder is once I go to some app and then back to mine, then turning off/on screen has no effect. Everything keeps working fine.

If you need some more things like some code parts from my app or stuff like that I will happily provide it for fixing this issue.

**Comment by alejouribesanchez** [comment]
+1

**Comment by gordonfreemanix** [comment]
+1 @hanks-zyh
